### ISSUE TITLE
Numerical Reproducibility against Hairer's dop853

### ISSUE THREAD

**Issue by Lima-Lima** [jacobwilliams/dop853#2]
@jacobwilliams , 

I'm finding, in running a VanDerPol example setup in Hairer's version and here that there is not numerical reproducibility (nor near-reproducibility) between the implementations of the method.

Do expect reproducibility? If so, I'll continue to search for any configuration differences in my test. If not, can you comment on the causes?

Thanks.

**Comment by jacobwilliams** [comment]
I think the one I have here uses a slightly different equation than Hairer's. See the comment in the header. So, it's not meant to be the same test, so it will be different.

**Comment by Lima-Lima** [comment]
Thanks Jacob. Yes, I recognize the parameters and initial conditions are different between the two examples and had corrected for this. 

Did you investigate reproducibility at any time by applying each method to an identical problem?

**Comment by jacobwilliams** [comment]
Yes, I get the same results from both codes (see the test case I just committed for #3, which has the exact same test case as Hairer):

```
 X = 2.00    Y =  0.1763234540E+01 -0.8356886819E+00
```

Do you get something different?

**Comment by Lima-Lima** [comment]
Great, I do now get reproducibility. Looks like I had a configuration error. 

Tested both with and without each optimization levels and -ffast-math, everything clear. 

Thanks for modernizing this method and sharing. It's appreciated!
