### ISSUE TITLE
Should `iout` be a public member of the integrator class?

### ISSUE THREAD

**Issue by ivan-pi** [jacobwilliams/dop853#4]
According to the current interface, the user will typically need to supply different `solout` functions for different values of `iout`. Alternatively, the `iout` can be set in a global scope and used in the call to the integrator and within the scope of the `solout` subroutine, e.g.:

```fortran
integer :: iout

call ode%integrate(t,y,tend,rtol,atol,iout=iout,idid=idid)

contains

  subroutine solout(me,nr,told,t,y,irtrn,tout)
  
    if (iout == 1) then

    else if (iout == 2) then

    else if (iout == 3) then

    end if

  end subroutine
end
```

If `iout` were a public member of the integrator class then we could use the value `me%iout` and eliminate the need for multiple `solout` subroutines, or the use of global variables.

What do you think?

**Comment by jacobwilliams** [comment]
That seems reasonable. probably I'd want to do it as a getter function: e.g. `if (me%iout())` (or use some more meaningful name).

**Comment by jacobwilliams** [comment]
Or just add an optional `iout` argument to the existing `get_dop853_info` function.
